### ISSUE TITLE
1.16.5 Server Crash On Startup

### ISSUE THREAD

**Issue by DeltaWolf7** [Azmalent/terra-incognita#54]
Hi,

The below exception is thrown on the latest version of TerraIncognita running on a dedicated server during start up.

TC: 1.7.1
Forge: 36.2.22
Cuneiform: 1.2.5

at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_311] {}
-- MOD terraincognita --
Details:
	Caused by 0: java.lang.BootstrapMethodError: java.lang.NoSuchMethodError: azmalent.terraincognita.common.inventory.BasketContainer.createOnClientSide(ILnet/minecraft/entity/player/PlayerInventory;Lnet/minecraft/network/PacketBuffer;)Lazmalent/terraincognita/common/inventory/BasketContainer;
		at azmalent.terraincognita.common.registry.ModContainers.lambda$static$0(ModContainers.java:14) ~[terraincognita:1.7.1] {re:classloading}
		at net.minecraftforge.registries.DeferredRegister.lambda$register$0(DeferredRegister.java:124) ~[forge:?] {re:classloading}
		at net.minecraftforge.registries.DeferredRegister.addEntries(DeferredRegister.java:200) ~[forge:?] {re:classloading}
		at net.minecraftforge.registries.DeferredRegister.access$000(DeferredRegister.java:61) ~[forge:?] {re:classloading}
		at net.minecraftforge.registries.DeferredRegister$EventDispatcher.handleEvent(DeferredRegister.java:172) ~[forge:?] {re:classloading}
		at net.minecraftforge.eventbus.ASMEventHandler_10_EventDispatcher_handleEvent_Register.invoke(.dynamic) ~[?:?] {}
		at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}

**Comment by Azmalent** [comment]
My bad! Please try 1.7.1.1.

**Comment by DeltaWolf7** [comment]
Wow, very fast response. That's spot on, fixed. Keep up the amazing work.
