### ISSUE TITLE
Apple Tree Client Desync

### ISSUE THREAD

**Issue by WenXin20** [Azmalent/terra-incognita#8]
`Minecraft v1.16.5`
`Forge v36.0.13`
`Terra Incognita v1.4.1`

Growing the apple sapling causes a desync with the server.
The hitbox of the apple is also not aligned.
<details>
  <summary>Log Error</summary>
  
  ```javascript
[13:11:17] [Render thread/FATAL]: Error executing task on Client
java.lang.NullPointerException: null
	at net.minecraft.world.World.func_241211_a_(World.java:186) ~[?:?]
	at net.minecraft.world.World.func_180501_a(World.java:176) ~[?:?]
	at net.minecraft.client.world.ClientWorld.func_180501_a(ClientWorld.java:736) ~[?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.lambda$handleMultiBlockChange$0(ClientPlayNetHandler.java:717) ~[?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler$$Lambda$35483/288540833.accept(Unknown Source) ~[?:?]
	at net.minecraft.network.play.server.SMultiBlockChangePacket.func_244310_a(SourceFile:79) ~[?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147287_a(ClientPlayNetHandler.java:716) ~[?:?]
	at net.minecraft.network.play.server.SMultiBlockChangePacket.func_148833_a(SourceFile:71) ~[?:?]
	at net.minecraft.network.play.server.SMultiBlockChangePacket.func_148833_a(SourceFile:15) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:34) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$33601/1173364206.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:172) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:134) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:115) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.0.13.jar:36.0]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$490/224280405.call(Unknown Source) [forge-1.16.5-36.0.13.jar:36.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
  ```
  
</details>

**Comment by Azurewren** [comment]
`Minecraft v1.18.2`
`Forge v40.1.84`
`Terra Incognita v1.18.2-2.0 (Beta 4)`

I have just experienced this myself. I grew the apple sapling, and was standing next to it. I then got a Connection Lost 'Internal server error'. Every time I try to log back in it kicks me back off the server with the same message.

<details><summary>Server logs:</summary>

```java
net.minecraft.ReportedException: Ticking player
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:502) ~[server-1.18.2-20220404.173914-srg.jar%23241!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:207) ~[server-1.18.2-20220404.173914-srg.jar%23241!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:245) ~[server-1.18.2-20220404.173914-srg.jar%23241!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[server-1.18.2-20220404.173914-srg.jar%23241!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916) ~[server-1.18.2-20220404.173914-srg.jar%23241!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326) ~[server-1.18.2-20220404.173914-srg.jar%23241!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[server-1.18.2-20220404.173914-srg.jar%23241!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[server-1.18.2-20220404.173914-srg.jar%23241!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23241!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: Cannot set property IntegerProperty{name=age, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7]} to 8 on Block{terraincognita:apple}, it is not an allowed value
	at net.minecraft.world.level.block.state.StateHolder.m_61124_(StateHolder.java:125) ~[server-1.18.2-20220404.173914-srg.jar%23241!/:?]
	at azmalent.terraincognita.common.block.fruit.AbstractFruitBlock.m_7455_(AbstractFruitBlock.java:95) ~[terraincognita-1.18.2-2.0.jar%23210!/:2.0]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60735_(BlockBehaviour.java:681) ~[server-1.18.2-20220404.173914-srg.jar%23241!/:?]
	at com.kwpugh.gobber2.util.GrowingUtil.growCrops(GrowingUtil.java:35) ~[Gobber2-Forge-1.18.2-2.6.37.jar%23129!/:2.6.37]
	at com.kwpugh.gobber2.items.rings.ItemCustomRingFarmer.m_6883_(ItemCustomRingFarmer.java:58) ~[Gobber2-Forge-1.18.2-2.6.37.jar%23129!/:2.6.37]
	at net.minecraft.world.item.ItemStack.m_41666_(ItemStack.java:494) ~[server-1.18.2-20220404.173914-srg.jar%23241!/:?]
	at net.minecraft.world.entity.player.Inventory.m_36068_(Inventory.java:229) ~[server-1.18.2-20220404.173914-srg.jar%23241!/:?]
	at net.minecraft.world.entity.player.Player.m_8107_(Player.java:490) ~[server-1.18.2-20220404.173914-srg.jar%23241!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2253) ~[server-1.18.2-20220404.173914-srg.jar%23241!/:?]
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:235) ~[server-1.18.2-20220404.173914-srg.jar%23241!/:?]
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439) ~[server-1.18.2-20220404.173914-srg.jar%23241!/:?]
	... 9 more
[20Dec2022 17:19:19.942] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: Player lost connection: Internal server error

```

</details>

**Comment by Azmalent** [comment]
Oops, didn't mean to close it.
Please try the new version, this issue should hopefully be fixed.
